export const langText = {
  ru: {
    subtitle: "Для ПРО-трейдеров",
    title: "Разместите свою стратегию на KYT чтобы привлечь новых клиентов",
    text: "Мы заботимся обо всем остальном с инвестором.",
    button: "Узнать больше",
    caption: "Как начать",
    step1: "Создать аккаунт на KYT",
    step2: "Оплатить подписку",
    step3: "Подключить API от торгового счёта",
    createAccBTn: "Создать аккаунт",
  },
  en: {
    subtitle: "For PRO traders",
    title: "Place your strategy on KYT to attract new clients",
    button: "Learn more",
    text: "We care about everything with the investor.",
    caption: "How to start",
    step1: "Create an account on KYT",
    step2: "Pay for a subscription",
    step3: "Connect API from the trading account",
    createAccBTn: "Create an account",
  },
  de: {
    subtitle: "For PRO traders",
    title: "Platzieren Sie Ihre Strategie auf KYT, um neue Kunden zu gewinnen",
    text: "Wir betrachten alles mit dem Investor.",
    button: "Lernen Sie mehr",
    caption: "Wie man beginnt",
    step1: "Erstellen Sie ein Konto auf KYT",
    step2: "Bezahlen Sie für eine Abonnement",
    step3: "Verbinden Sie API von dem Handelskonto",
    createAccBTn: "Create an account",
  },
  es: {
    subtitle: "For PRO traders",
    title: "Place your strategy on KYT to attract new clients",
    text: "We care about everything with the investor.",
    button: "Learn more",
    caption: "How to start",
    step1: "Create an account on KYT",
    step2: "Pay for a subscription",
    step3: "Connect API from the trading account",
    createAccBTn: "Create an account",
  },
};
