export const langText = {
  ru: {
    label1: "Для трейдера",
    label2: "Для инвестора",
    mainProblems: "Решает основные проблемы",
    investors: "трейдеров и инвесторов",
    cardData: [
      "Сложности в доказательстве точности и надежности вашей торговой истории",
      "Трата времени на подготовку отчетов для инвесторов и заинтересованных сторон",
      "Проблемы с привлечением инвесторов к вашим торговым стратегиям",
      "Отсутствие профессионального онлайн-присутствия для демонстрации вашего успеха в торговле",
      "Ощущение отсутствия связи и поиск сети единомышленников трейдеров",
      "Сложности и затраты, связанные с управлением несколькими счетами клиентов",
    ],
    cardOnes: [
      "Сложности в поиске надежных трейдеров с проверенной историей",
      "Слишком много времени уходит на анализ данных трейдеров",
      "Опасения насчет прозрачности и справедливости распределения прибыли",
      "Недостаток доступа к различным стратегиям для диверсификации портфеля",
      "Поиск сообщества инвесторов для обмена опытом",
      "Сложности в отслеживании нескольких инвестиций и их результатов",
    ],
    subtitle: "Для ПРО-трейдеров",
    title: "Разместите свою стратегию на KYT чтобы привлечь новых клиентов",
    text: "Мы заботимся обо всем остальном с инвестором.",
    button: "Узнать больше",
    caption: "Как начать",
    step1: "Создать аккаунт на KYT",
    step2: "Оплатить подписку",
    step3: "Подключить API от торгового счёта",
    createAccBTn: "Создать аккаунт",
  },
  en: {
    label1: "For the trader",
    label2: "For the investor",
    investors: "traders and investors",
    mainProblems: "Solves the main problems",
    cardData: [
      "Difficulties in proving the accuracy and reliability of your trading history",
      "Spending time preparing reports for investors and stakeholders",
      "Issues with attracting investors to your trading strategies",
      "Lack of professional online presence to showcase your trading success",
      "Feeling disconnected and searching for a network of like-minded traders",
      "Difficulties and costs associated with managing multiple client accounts",
    ],
    cardOnes: [
      "Difficulties in finding reliable traders with a proven track record",
      "Too much time is spent analyzing trader data",
      "Concerns about the transparency and fairness of profit distribution",
      "Lack of access to various strategies for portfolio diversification",
      "Searching for an investor community to share experiences",
      "Difficulties in tracking multiple investments and their outcomes",
    ],
    subtitle: "For PRO traders",
    title: "Place your strategy on KYT to attract new clients",
    button: "Learn more",
    text: "We care about everything with the investor.",
    caption: "How to start",
    step1: "Create an account on KYT",
    step2: "Pay for a subscription",
    step3: "Connect API from the trading account",
    createAccBTn: "Create an account",
  },
  de: {
    label1: "Para el trader",
    label2: "Para el inversor",
    investors: "händler und Investoren",
    mainProblems: "Löst die Hauptprobleme",
    cardData: [
      "Schwierigkeiten beim Nachweis der Genauigkeit und Zuverlässigkeit Ihrer Handelshistorie",
      "Zeitaufwand für die Erstellung von Berichten für Investoren und Interessengruppen",
      "Probleme bei der Gewinnung von Investoren für Ihre Handelsstrategien",
      "Mangel an professioneller Online-Präsenz, um Ihren Handelserfolg zu präsentieren",
      "Gefühl der Isolation und Suche nach einem Netzwerk gleichgesinnter Händler",
      "Schwierigkeiten und Kosten im Zusammenhang mit der Verwaltung mehrerer Kundenkonten",
    ],
    cardOnes: [
      "Schwierigkeiten bei der Suche nach zuverlässigen Händlern mit nachgewiesener Geschichte",
      "Zu viel Zeit wird für die Analyse von Händlerinformationen aufgewendet",
      "Bedenken hinsichtlich der Transparenz und Fairness der Gewinnverteilung",
      "Mangelnder Zugang zu verschiedenen Strategien zur Portfoliodiversifikation",
      "Suche nach einer Investorengemeinschaft zum Erfahrungsaustausch",
      "Schwierigkeiten bei der Nachverfolgung mehrerer Investitionen und ihrer Ergebnisse",
    ],
    subtitle: "For PRO traders",
    title: "Platzieren Sie Ihre Strategie auf KYT, um neue Kunden zu gewinnen",
    text: "Wir betrachten alles mit dem Investor.",
    button: "Lernen Sie mehr",
    caption: "Wie man beginnt",
    step1: "Erstellen Sie ein Konto auf KYT",
    step2: "Bezahlen Sie für eine Abonnement",
    step3: "Verbinden Sie API von dem Handelskonto",
    createAccBTn: "Create an account",
  },
  es: {
    label1: "Für Händler",
    label2: "Für Investoren",
    investors: "traders e inversores",
    mainProblems: "Resuelve los problemas principales",
    cardData: [
      "Dificultades para demostrar la precisión y confiabilidad de su historial de trading",
      "Pérdida de tiempo preparando informes para inversores y partes interesadas",
      "Problemas para atraer inversores a sus estrategias de trading",
      "Falta de presencia profesional en línea para mostrar su éxito en el trading",
      "Sensación de desconexión y búsqueda de una red de traders con ideas afines",
      "Dificultades y costos asociados con la gestión de múltiples cuentas de clientes"
    ],
    cardOnes: [
      "Dificultades para encontrar traders confiables con historial comprobado",
      "Se necesita demasiado tiempo para analizar los datos de los traders",
      "Preocupaciones sobre la transparencia y equidad en la distribución de beneficios",
      "Falta de acceso a diferentes estrategias para diversificar la cartera",
      "Búsqueda de una comunidad de inversores para compartir experiencias",
      "Dificultades para rastrear múltiples inversiones y sus resultados",
    ],
    subtitle: "For PRO traders",
    title: "Place your strategy on KYT to attract new clients",
    text: "We care about everything with the investor.",
    button: "Learn more",
    caption: "How to start",
    step1: "Create an account on KYT",
    step2: "Pay for a subscription",
    step3: "Connect API from the trading account",
    createAccBTn: "Create an account",
  },
};
