export const translations = {
    en: {
        newDeclaration: "New declaration",
        iDeclaration: "Investment declaration",
        publish: "Publish",
        statistics: "Statistics confirmation",
        KYTtraders: "Attach your portfolio from KYT Traders Passport",
        selectAportfolio: "Select a portfolio",
        startDate: "Start date",
        started: "The day you started trading by the current rules of your investment declaration",
        name: "Name",
        nameOfYour: "The name of your declaration",
        sDate: "Select a date",
        description: "Description",
        english: "English",
        russian: "Русский",
        whyInvestors: "Why investors should follow your strategy",
        mDirection: "Market Direction",
        cTrend: "Counter Trend",
        mNeutral: "Market Neutral",
        trend: "Trend",
        aDirection: "Any Direction",
        other: "Other",
        mType: "Management Type",
        algo: "Algo",
        dType: "Mixed Type",
        hTrading: "Hand Trading",
        tSpeed: "Trading Speed",
        HFT: "HFT",
        scalping: "Scalping",
        sTerm: "Short Term",
        mTerm: "Mid Term",
        lTerm: "Long Term",
        pType: "Position Type",
        long: "Long",
        short: "Short",
        lShort: "Long & Short",
        rType: "Risk Type",
        hRisk: "High Risk",
        mRisk: "Medium Risk",
        conservative: "Conservative",
        gType: "Margin Type",
        cross: "Cross",
        isolated: "Isolated",
        mixed: "Mixed",
        lType: "Lot Type",
        static: "Static",
        dynamic: "Dynamic",
        mLot: "Minimal Lot",
        theMinimum: " The minimum deposit amount for which the strategy can enter a position. For example, if you have a distributed entry position or grid, then the minimum lot will be the volume of one order in the grid.",
        mLoad: "Max Deposit Load",
        hMode: "Hedge Mode",
        yes: "Yes",
        no: "No",
        mMode: "Margin Mode",
        sAsset: "Single Asset",
        mAsset: "Multi Asset",
        lCap: "Liquidity Cap",
        mdeposit: "Minimum deposit",
        fDeposit: "Minimum deposit for the strategy to work correctly at the settings specified in the current declaration",
        uPairs: "Used Trading Pairs",
        isThere: "Is there a limit to the maximum possible drawdown per day?",
        mDrawdown: "Maximum drawdown limit per day",
        aMaximum: "Is there a maximum drawdown limit?",
        mLimit: "Maximum drawdown limit",
        optimization: "Strategy Optimization",
        eSoftware: "Execution Software",
        oSoftware: "Optimization Software",
    },
    ru: {
        newDeclaration: "Новая декларация",
        iDeclaration: "Инвестиционная декларация",
        publish: "Опубликовать",
        statistics: "Подтверждение статистики",
        KYTtraders: "Приложите портфель из KYT Traders Passport",
        selectAportfolio: "Выберите портфель",
        startDate: "Дата начала",
        started: "День, когда вы начали торговать по текущим правилам вашей инвестиционной декларации",
        name: "Название",
        nameOfYour: "Название вашей декларации",
        sDate: "Выберите дату",
        description: "Описание",
        english: "Английский",
        russian: "Русский",
        whyInvestors: "Почему инвесторы должны следовать вашей стратегии",
        mDirection: "Направление рынка",
        cTrend: "Против тренда",
        mNeutral: "Рыночный нейтралитет",
        trend: "Тренд",
        aDirection: "Любое направление",
        other: "Другое",
        mType: "Тип управления",
        algo: "Алго",
        dType: "Смешанный тип",
        hTrading: "Ручная торговля",
        tSpeed: "Скорость торговли",
        HFT: "HFT",
        scalping: "Скальпинг",
        sTerm: "Краткосрочный",
        mTerm: "Среднесрочный",
        lTerm: "Долгосрочный",
        pType: "Тип позиции",
        long: "Длинная",
        short: "Короткая",
        lShort: "Длинная и короткая",
        rType: "Тип риска",
        hRisk: "Высокий риск",
        mRisk: "Средний риск",
        conservative: "Консервативный",
        gType: "Тип маржи",
        cross: "Кросс",
        isolated: "Изолированная",
        mixed: "Смешанная",
        lType: "Тип лота",
        static: "Статичный",
        dynamic: "Динамичный",
        mLot: "Минимальный лот",
        theMinimum: "Минимальная сумма депозита для входа в позицию по стратегии. Например, если вы используете распределенный вход или сетку, то минимальный лот будет объемом одного ордера в сетке.",
        mLoad: "Максимальная загрузка депозита",
        hMode: "Хедж-режим",
        yes: "Да",
        no: "Нет",
        mMode: "Маржинальный режим",
        sAsset: "Один актив",
        mAsset: "Мульти-актив",
        lCap: "Ликвидный лимит",
        mdeposit: "Минимальный депозит",
        fDeposit: "Минимальный депозит для корректной работы стратегии с указанными параметрами",
        uPairs: "Используемые торговые пары",
        isThere: "Есть ли лимит на максимальную просадку за день?",
        mDrawdown: "Лимит максимальной просадки за день",
        aMaximum: "Есть ли лимит максимальной просадки?",
        mLimit: "Лимит максимальной просадки",
        optimization: "Оптимизация стратегии",
        eSoftware: "ПО для выполнения",
        oSoftware: "ПО для оптимизации",
    },
    es: {
        newDeclaration: "Nueva declaración",
        iDeclaration: "Declaración de inversión",
        publish: "Publicar",
        statistics: "Confirmación de estadísticas",
        KYTtraders: "Adjunte su portafolio de KYT Traders Passport",
        selectAportfolio: "Seleccione un portafolio",
        startDate: "Fecha de inicio",
        started: "El día que comenzó a operar bajo las reglas actuales de su declaración de inversión",
        name: "Nombre",
        nameOfYour: "El nombre de su declaración",
        sDate: "Seleccione una fecha",
        description: "Descripción",
        english: "Inglés",
        russian: "Ruso",
        whyInvestors: "Por qué los inversores deberían seguir su estrategia",
        mDirection: "Dirección del mercado",
        cTrend: "Contra tendencia",
        mNeutral: "Neutralidad del mercado",
        trend: "Tendencia",
        aDirection: "Cualquier dirección",
        other: "Otro",
        mType: "Tipo de gestión",
        algo: "Algorítmico",
        dType: "Tipo mixto",
        hTrading: "Operaciones manuales",
        tSpeed: "Velocidad de operación",
        HFT: "HFT",
        scalping: "Scalping",
        sTerm: "Corto plazo",
        mTerm: "Medio plazo",
        lTerm: "Largo plazo",
        pType: "Tipo de posición",
        long: "Largo",
        short: "Corto",
        lShort: "Largo y corto",
        rType: "Tipo de riesgo",
        hRisk: "Alto riesgo",
        mRisk: "Riesgo medio",
        conservative: "Conservador",
        gType: "Tipo de margen",
        cross: "Cruzado",
        isolated: "Aislado",
        mixed: "Mixto",
        lType: "Tipo de lote",
        static: "Estático",
        dynamic: "Dinámico",
        mLot: "Lote mínimo",
        theMinimum: "El monto mínimo del depósito para que la estrategia pueda entrar en una posición. Por ejemplo, si tiene una posición de entrada distribuida o una cuadrícula, el lote mínimo será el volumen de una orden en la cuadrícula.",
        mLoad: "Carga máxima del depósito",
        hMode: "Modo de cobertura",
        yes: "Sí",
        no: "No",
        mMode: "Modo de margen",
        sAsset: "Activo único",
        mAsset: "Multi-activo",
        lCap: "Límite de liquidez",
        mdeposit: "Depósito mínimo",
        fDeposit: "Depósito mínimo para que la estrategia funcione correctamente con la configuración especificada en la declaración actual",
        uPairs: "Pares comerciales utilizados",
        isThere: "¿Existe un límite para la caída máxima diaria?",
        mDrawdown: "Límite de caída máxima diaria",
        aMaximum: "¿Existe un límite máximo de caída?",
        mLimit: "Límite máximo de caída",
        optimization: "Optimización de la estrategia",
        eSoftware: "Software de ejecución",
        oSoftware: "Software de optimización",
    },
    de: {
        newDeclaration: "Neue Erklärung",
        iDeclaration: "Investitionserklärung",
        publish: "Veröffentlichen",
        statistics: "Statistikbestätigung",
        KYTtraders: "Fügen Sie Ihr Portfolio aus dem KYT Traders Passport bei",
        selectAportfolio: "Wählen Sie ein Portfolio",
        startDate: "Startdatum",
        started: "Der Tag, an dem Sie mit den aktuellen Regeln Ihrer Investitionserklärung gehandelt haben",
        name: "Name",
        nameOfYour: "Der Name Ihrer Erklärung",
        sDate: "Wählen Sie ein Datum",
        description: "Beschreibung",
        english: "Englisch",
        russian: "Russisch",
        whyInvestors: "Warum sollten Investoren Ihrer Strategie folgen?",
        mDirection: "Marktrichtung",
        cTrend: "Gegen den Trend",
        mNeutral: "Marktneutralität",
        trend: "Trend",
        aDirection: "Beliebige Richtung",
        other: "Andere",
        mType: "Verwaltungstyp",
        algo: "Algo",
        dType: "Gemischter Typ",
        hTrading: "Manueller Handel",
        tSpeed: "Handelsgeschwindigkeit",
        HFT: "HFT",
        scalping: "Scalping",
        sTerm: "Kurzfristig",
        mTerm: "Mittelfristig",
        lTerm: "Langfristig",
        pType: "Positionstyp",
        long: "Long",
        short: "Short",
        lShort: "Long & Short",
        rType: "Risikotyp",
        hRisk: "Hohes Risiko",
        mRisk: "Mittleres Risiko",
        conservative: "Konservativ",
        gType: "Margentyp",
        cross: "Cross",
        isolated: "Isoliert",
        mixed: "Gemischt",
        lType: "Losgröße",
        static: "Statisch",
        dynamic: "Dynamisch",
        mLot: "Minimale Losgröße",
        theMinimum: "Der minimale Einzahlungsbetrag, für den die Strategie eine Position eingehen kann. Zum Beispiel, wenn Sie eine verteilte Einstiegsposition oder ein Grid verwenden, wird das minimale Los das Volumen einer Order im Grid sein.",
        mLoad: "Maximale Einzahlungsbelastung",
        hMode: "Hedge-Modus",
        yes: "Ja",
        no: "Nein",
        mMode: "Margin-Modus",
        sAsset: "Einzelner Vermögenswert",
        mAsset: "Multi-Asset",
        lCap: "Liquiditätslimit",
        mdeposit: "Mindestanlage",
        fDeposit: "Mindestanlage, damit die Strategie mit den in der aktuellen Erklärung angegebenen Einstellungen korrekt funktioniert",
        uPairs: "Verwendete Handelspaare",
        isThere: "Gibt es ein Limit für den maximalen Tagesverlust?",
        mDrawdown: "Maximales Tagesverlustlimit",
        aMaximum: "Gibt es ein maximales Verlustlimit?",
        mLimit: "Maximales Verlustlimit",
        optimization: "Strategieoptimierung",
        eSoftware: "Ausführungssoftware",
        oSoftware: "Optimierungssoftware",
    },
};