// Tarjima obyektini aniqlash


export const translations = {
    en: {
        kytDescription: "For professional traders and investors within the crypto market.",
        passportTitle: "Traders Passport",
        passportDescription: "Worldwide Independent confirmation of traders' results",
        login: "Log In",
        signup: "Sign Up",
        profile: "Profile",
        about: "About",
        products: "Products",
        faq: "FAQ",
        traderCabinet: "Trader's Cabinet",
        rating: "Rating",
        throwError: "Invalid token format",
        dashboard: "Dashboard",
        logOut: "Successfully logged out!",
        logoutFailed: "Logout failed. Please try again.",
    },
    ru: {
        kytDescription: "Для профессиональных трейдеров и инвесторов на криптовалютном рынке.",
        passportTitle: "Паспорт трейдера",
        passportDescription: "Международное подтверждение результатов трейдеров",
        login: "Войти",
        signup: "Регистрация",
        about: "О нас",
        profile: "Профиль",
        products: "Продукты",
        faq: "Вопросы и ответы",
        traderCabinet: "Кабинет трейдера",
        rating: "Рейтинг",
        throwError: "Неверный формат токена",
        dashboard: "Панель управления",
        logOut: "Вы успешно вышли из системы!",
        logoutFailed: "Не удалось выйти из системы. Пожалуйста, попробуйте снова.",
    },
    es: {
        kytDescription: "Para traders profesionales e inversores en el mercado de criptomonedas.",
        passportTitle: "Pasaporte de Comerciante",
        passportDescription: "Confirmación independiente de resultados de traders a nivel mundial",
        login: "Iniciar sesión",
        signup: "Registrarse",
        about: "Acerca de",
        products: "Productos",
        profile: "Perfil",
        faq: "Preguntas frecuentes",
        traderCabinet: "Gabinete del Comerciante",
        rating: "Calificación",
        throwError: "Formato de token inválido",
        dashboard: "Tablero de control",
        logOut: "¡Cierre de sesión exitoso!",
        logoutFailed: "Error al cerrar sesión. Por favor, inténtelo de nuevo.",
    },
    de: {
        kytDescription: "Für professionelle Trader und Investoren auf dem Kryptomarkt.",
        passportTitle: "Trader-Pass",
        passportDescription: "Weltweite unabhängige Bestätigung der Trader-Ergebnisse",
        login: "Einloggen",
        signup: "Anmelden",
        about: "Über uns",
        products: "Produkte",
        profile: "Profil",
        faq: "FAQ",
        traderCabinet: "Trader-Kabinett",
        rating: "Bewertung",
        throwError: "Ungültiges Token-Format",
        dashboard: "Instrumententafel",
        logOut: "Erfolgreich abgemeldet!",
        logoutFailed: "Abmelden fehlgeschlagen. Bitte versuchen Sie es erneut.",
    },
};

