export const translations = {
    en: {
        myKeys: "My Keys",
        contentComingSoon: "Content is coming soon, stay tuned!",
        connectFirstKey: "Connect your first exchange API key to access trading stats and build your portfolio.",
        addKey: "Add key",
        myPortfolios: "My Portfolios",
        nothingHereYet: "There's nothing here yet",
        buildPortfolio: "Build a portfolio to showcase to clients or take part in the trader ranking.",
        addPortfolio: "Add portfolio",
        favorites: "Favorites",
        addToFavorites: "Add your preferred strategy to your favorites",
        visitLeaderboardPage: "Visit the user's page from the leaderboard and add your favorite strategy to your list of favorites.",
        goToLeaderboard: "Go to leaderboard page",
    },
    ru: {
        myKeys: "Мои ключи",
        contentComingSoon: "Контент скоро появится, следите за обновлениями!",
        connectFirstKey: "Подключите свой первый API-ключ биржи, чтобы получить доступ к статистике торговли и создать портфель.",
        addKey: "Добавить ключ",
        myPortfolios: "Мои портфели",
        nothingHereYet: "Здесь пока ничего нет",
        buildPortfolio: "Создайте портфель, чтобы продемонстрировать его клиентам или принять участие в рейтинге трейдеров.",
        addPortfolio: "Добавить портфель",
        favorites: "Избранное",
        addToFavorites: "Добавьте свою предпочтительную стратегию в избранное",
        visitLeaderboardPage: "Посетите страницу пользователя в таблице лидеров и добавьте свою любимую стратегию в список избранного.",
        goToLeaderboard: "Перейти на страницу таблицы лидеров",
    },
    de: {
        myKeys: "Meine Schlüssel",
        contentComingSoon: "Inhalt kommt bald, bleiben Sie dran!",
        connectFirstKey: "Verbinden Sie Ihren ersten Exchange-API-Schlüssel, um auf Handelsstatistiken zuzugreifen und Ihr Portfolio aufzubauen.",
        addKey: "Schlüssel hinzufügen",
        myPortfolios: "Meine Portfolios",
        nothingHereYet: "Hier ist noch nichts",
        buildPortfolio: "Erstellen Sie ein Portfolio, um es Kunden zu zeigen oder an der Trader-Rangliste teilzunehmen.",
        addPortfolio: "Portfolio hinzufügen",
        favorites: "Favoriten",
        addToFavorites: "Fügen Sie Ihre bevorzugte Strategie zu Ihren Favoriten hinzu",
        visitLeaderboardPage: "Besuchen Sie die Benutzerseite auf der Rangliste und fügen Sie Ihre bevorzugte Strategie zu Ihrer Favoritenliste hinzu.",
        goToLeaderboard: "Zur Ranglistenseite gehen",
    },
    es: {
        myKeys: "Mis claves",
        contentComingSoon: "¡El contenido llegará pronto, mantente atento!",
        connectFirstKey: "Conecta tu primera clave API de intercambio para acceder a estadísticas de trading y construir tu portafolio.",
        addKey: "Agregar clave",
        myPortfolios: "Mis portafolios",
        nothingHereYet: "Aún no hay nada aquí",
        buildPortfolio: "Crea un portafolio para mostrarlo a los clientes o participar en el ranking de traders.",
        addPortfolio: "Agregar portafolio",
        favorites: "Favoritos",
        addToFavorites: "Agrega tu estrategia preferida a tus favoritos",
        visitLeaderboardPage: "Visita la página del usuario en la tabla de clasificación y agrega tu estrategia favorita a tu lista de favoritos.",
        goToLeaderboard: "Ir a la página de la tabla de clasificación",
    },
};
