export const translations = {
  en: {
    tooltipReturn: "Total return percentage achieved",
    tooltipDrawDown: "Maximum drawdown percentage",
    tooltipMinDeposit: "Minimum deposit required",
    tooltipProfit: "Profit in dollars",
    labelReturn: "Margin Balance",
    labelDrawDown: "Profit, All",
    labelMinDeposit: "MDD",
    profitLabel: "Profit($)",
    startedAt: "Started at",
    days: "days",
    view: "View",
    result: "Result",
  },
  ru: {
    tooltipReturn: "Достигнутый процент общей прибыли",
    tooltipDrawDown: "Максимальный процент просадки",
    tooltipMinDeposit: "Требуемый минимальный депозит",
    tooltipProfit: "Прибыль в долларах",
    labelReturn: "Маржинальный баланс",
    labelDrawDown: "Прибыль, Всего",
    labelMinDeposit: "MDD",
    profitLabel: "Прибыль($)",
    startedAt: "Начало",
    days: "дней",
    view: "Посмотреть",
    result: "Результат",
  },
  es: {
    tooltipReturn: "Porcentaje de retorno total alcanzado",
    tooltipDrawDown: "Porcentaje máximo de reducción",
    tooltipMinDeposit: "Depósito mínimo requerido",
    tooltipProfit: "Beneficio en dólares",
    labelReturn: "Balance de margen",
    labelDrawDown: "Beneficio, Todo",
    labelMinDeposit: "MDD",
    profitLabel: "Beneficio($)",
    startedAt: "Comenzado en",
    days: "días",
    view: "Ver",
    result: "Resultado",
  },
  de: {
    tooltipReturn: "Erreichte Gesamt-Rendite in Prozent",
    tooltipDrawDown: "Maximale Drawdown-Prozentzahl",
    tooltipMinDeposit: "Erforderliche Mindesteinzahlung",
    tooltipProfit: "Gewinn in Dollar",
    labelReturn: "Margin-Bilanz",
    labelDrawDown: "Gewinn, Alle",
    labelMinDeposit: "MDD",
    profitLabel: "Gewinn($)",
    startedAt: "Gestartet am",
    days: "Tage",
    view: "Ansicht",
    result: "Ergebnis",
  },
};
