export const translations = {
    //     Nemischa (German): Statistik
    // Inglizcha (English): Statistics
    // Ispancha (Spanish): Estadística
    // Ruscha (Russian): Статистика
    en: {
        lite: "Lite",
        little: "A little",
        hour: "Hour",
        day: "Day",
        week: "Week",
        kIndicators: "Key indicators",
        main: "Statistics",
        investment: "Investment",
        trades: "Trades",
        views: "views",
    },
    ru: {
        lite: "Лёгкий",
        little: "Немного",
        hour: "Час",
        day: "День",
        week: "Неделя",
        kIndicators: "Ключевые показатели",
        main: "Статистика",
        investment: "Инвестиции",
        trades: "Сделки",
        views: "просмотры",
    },
    es: {
        lite: "Ligero",
        little: "Un poco",
        hour: "Hora",
        day: "Día",
        week: "Semana",
        kIndicators: "Indicadores clave",
        main: "Estadística",
        investment: "Inversión",
        trades: "Comercios",
        views: "vistas",
    },
    de: {
        lite: "Leicht",
        little: "Ein wenig",
        hour: "Stunde",
        day: "Tag",
        week: "Woche",
        kIndicators: "Schlüsselindikatoren",
        main: "Statistik",
        investment: "Investition",
        trades: "Handel",
        views: "Ansichten"
    },
};

export const checkboxData = [
    {
        key: "benchmarkBTC",
        label: {
            en: "Benchmark BTC",
            ru: "Бенчмарк BTC",
            es: "Referencia BTC",
            de: "Benchmark BTC"
        },
        color: "#FFD700"
    },
    {
        key: "return",
        label: {
            en: "Return (%)",
            ru: "Доходность (%)",
            es: "Retorno (%)",
            de: "Rendite (%)"
        },
        color: "#FFA500"
    },
    {
        key: "realizedReturn",
        label: {
            en: "Realized Return",
            ru: "Реализованный доход",
            es: "Retorno realizado",
            de: "Realisierte Rendite"
        },
        color: "#1E90FF"
    },
    {
        key: "marginBalance",
        label: {
            en: "Margin Balance",
            ru: "Маржинальный баланс",
            es: "Saldo de margen",
            de: "Margenguthaben"
        },
        color: "#3CB371"
    },
    {
        key: "balance",
        label: {
            en: "Balance",
            ru: "Баланс",
            es: "Saldo",
            de: "Guthaben"
        },
        color: "#A52A2A"
    },
    {
        key: "plByday",
        label: {
            en: "P\\L by day",
            ru: "Прибыль/Убыток за день",
            es: "P\\L por día",
            de: "P\\L pro Tag"
        },
        color: "#20B2AA"
    },
    {
        key: "profit",
        label: {
            en: "Profit ($)",
            ru: "Прибыль ($)",
            es: "Beneficio ($)",
            de: "Gewinn ($)"
        },
        color: "#4B0082"
    },
    {
        key: "usedLeverage",
        label: {
            en: "Used Leverage",
            ru: "Используемое плечо",
            es: "Apalancamiento utilizado",
            de: "Genutzter Hebel"
        },
        color: "#9370DB"
    },
    {
        key: "drawDown",
        label: {
            en: "DrawDown",
            ru: "Просадка",
            es: "Pérdida máxima",
            de: "Maximaler Verlust"
        },
        color: "#4169E1"
    },
    {
        key: "drawDownDuration",
        label: {
            en: "DrawDown Duration",
            ru: "Длительность просадки",
            es: "Duración de la pérdida",
            de: "Verlustdauer"
        },
        color: "#1E90FF"
    },
];

export const transInvestment = {
    en: {
        lifetimeExperience: "Lifetime Experience",
        sharpeRatio: "Sharpe Ratio",
        calmarRatio: "Calmar Ratio",
        sortinoRatio: "Sortino Ratio",
        ir: "IR",
        volatility: "Volatility",
        alphaRatio: "α Ratio",
        betaRatio: "β Ratio",
        treynorRatio: "Treynor Ratio",
        schwagerRatio: "Schwager Ratio",
        rSquared: "R²",
        mSquared: "M²",
        lifetimeExperienceDescription: "Very good",
        sharpeRatioDescription: "Excellent risk-adjusted performance",
        calmarRatioDescription: "High return per drawdown risk",
        sortinoRatioDescription: "Excellent downside risk-adjusted performance",
        irDescription: "Greatly outperforms benchmark",
        volatilityDescription: "Some fluctuations, moderate risk",
        alphaRatioDescription: "Greatly outperforms benchmark",
        betaRatioDescription: "Moves with market",
        treynorRatioDescription: "High return per market risk",
        schwagerRatioDescription: "Favorable balance of returns",
        rSquaredDescription: "Independent from benchmark",
        mSquaredDescription: "Significant risk-adjusted outperformance",
    },
    uz: {
        lifetimeExperience: "Umr bo'yi tajriba",
        sharpeRatio: "Sharpe nisbat",
        calmarRatio: "Calmar nisbat",
        sortinoRatio: "Sortino nisbat",
        ir: "IR",
        volatility: "Volatillik",
        alphaRatio: "α nisbat",
        betaRatio: "β nisbat",
        treynorRatio: "Treynor nisbat",
        schwagerRatio: "Schwager nisbat",
        rSquared: "R²",
        mSquared: "M²",
        lifetimeExperienceDescription: "Juda yaxshi",
        sharpeRatioDescription: "Yaxshi risk-adjusted ko'rsatkich",
        calmarRatioDescription: "Yuqori daromad, kichik xatarlik",
        sortinoRatioDescription: "Yuqori pastga qarab risk-adjusted ko'rsatkich",
        irDescription: "Benchmarkdan ancha yuqori ko'rsatkich",
        volatilityDescription: "Ba'zi o'zgarishlar, o'rtacha risk",
        alphaRatioDescription: "Benchmarkdan ancha yuqori ko'rsatkich",
        betaRatioDescription: "Bozor bilan harakat qiladi",
        treynorRatioDescription: "Bozor riskiga nisbatan yuqori daromad",
        schwagerRatioDescription: "Daromadlarning yaxshi balanslanganligi",
        rSquaredDescription: "Benchmarkdan mustaqil",
        mSquaredDescription: "Katta risk-adjusted daromad",
    },
    ru: {
        lifetimeExperience: "Опыт всей жизни",
        sharpeRatio: "Коэффициент Шарпа",
        calmarRatio: "Коэффициент Калмара",
        sortinoRatio: "Коэффициент Сортино",
        ir: "IR",
        volatility: "Волатильность",
        alphaRatio: "α коэффициент",
        betaRatio: "β коэффициент",
        treynorRatio: "Коэффициент Трейнора",
        schwagerRatio: "Коэффициент Швагера",
        rSquared: "R²",
        mSquared: "M²",
        lifetimeExperienceDescription: "Очень хорошо",
        sharpeRatioDescription: "Отличная производительность с учетом риска",
        calmarRatioDescription: "Высокая доходность при риске просадки",
        sortinoRatioDescription: "Отличная производительность с учетом риска вниз",
        irDescription: "Значительно превосходит эталон",
        volatilityDescription: "Некоторые колебания, умеренный риск",
        alphaRatioDescription: "Значительно превосходит эталон",
        betaRatioDescription: "Двигается с рынком",
        treynorRatioDescription: "Высокая доходность при рыночном риске",
        schwagerRatioDescription: "Благоприятный баланс доходности",
        rSquaredDescription: "Независим от эталона",
        mSquaredDescription: "Значительная доходность с учетом риска",
    },
    es: {
        lifetimeExperience: "Experiencia de toda la vida",
        sharpeRatio: "Índice de Sharpe",
        calmarRatio: "Índice de Calmar",
        sortinoRatio: "Índice de Sortino",
        ir: "IR",
        volatility: "Volatilidad",
        alphaRatio: "α Índice",
        betaRatio: "β Índice",
        treynorRatio: "Índice de Treynor",
        schwagerRatio: "Índice de Schwager",
        rSquared: "R²",
        mSquared: "M²",
        lifetimeExperienceDescription: "Muy bueno",
        sharpeRatioDescription: "Excelente rendimiento ajustado al riesgo",
        calmarRatioDescription: "Alta rentabilidad por riesgo de retroceso",
        sortinoRatioDescription: "Excelente rendimiento ajustado al riesgo a la baja",
        irDescription: "Supera significativamente el benchmark",
        volatilityDescription: "Algunas fluctuaciones, riesgo moderado",
        alphaRatioDescription: "Supera significativamente el benchmark",
        betaRatioDescription: "Se mueve con el mercado",
        treynorRatioDescription: "Alta rentabilidad por riesgo de mercado",
        schwagerRatioDescription: "Balance favorable de rendimientos",
        rSquaredDescription: "Independiente del benchmark",
        mSquaredDescription: "Supera significativamente el benchmark ajustado al riesgo",
    },
    de: {
        lifetimeExperience: "Lebenslange Erfahrung",
        sharpeRatio: "Sharpe-Verhältnis",
        calmarRatio: "Calmar-Verhältnis",
        sortinoRatio: "Sortino-Verhältnis",
        ir: "IR",
        volatility: "Volatilität",
        alphaRatio: "α Verhältnis",
        betaRatio: "β Verhältnis",
        treynorRatio: "Treynor-Verhältnis",
        schwagerRatio: "Schwager-Verhältnis",
        rSquared: "R²",
        mSquared: "M²",
        lifetimeExperienceDescription: "Sehr gut",
        sharpeRatioDescription: "Ausgezeichnete risikoadjustierte Leistung",
        calmarRatioDescription: "Hohe Rendite pro Rückschlagrisiko",
        sortinoRatioDescription: "Ausgezeichnete Leistung bei nach unten gerichteten Risiken",
        irDescription: "Übertrifft das Benchmark erheblich",
        volatilityDescription: "Einige Schwankungen, moderates Risiko",
        alphaRatioDescription: "Übertrifft das Benchmark erheblich",
        betaRatioDescription: "Bewegt sich mit dem Markt",
        treynorRatioDescription: "Hohe Rendite pro Marktrisiko",
        schwagerRatioDescription: "Günstige Balance der Renditen",
        rSquaredDescription: "Unabhängig vom Benchmark",
        mSquaredDescription: "Erheblicher risikoadjustierter Mehrwert",
    }
};

export const labelsBar = {
    usedLeverage: {
        en: "Used Leverage:",
        ru: "Используемое кредитное плечо:",
        de: "Verwendeter Hebel:",
        es: "Apalancamiento usado:",
    },
    longPositions: {
        en: "Long positions:",
        ru: "Длинные позиции:",
        de: "Long-Positionen:",
        es: "Posiciones largas:",
    },
    shortPositions: {
        en: "Short positions:",
        ru: "Короткие позиции:",
        de: "Short-Positionen:",
        es: "Posiciones cortas:",
    },
};

export const labels = {
    en: {
        benchmarkBTC: "Benchmark BTC",
        return: "Return (%)",
        realizedReturn: "Realized Return",
        plByDay: "P\\L by day",
        marginBalance: "Margin Balance",
        balance: "Balance",
        profit: "Profit ($)",
    },
    ru: {
        benchmarkBTC: "Бенчмарк BTC",
        return: "Доходность (%)",
        realizedReturn: "Реализованная доходность",
        plByDay: "П\\Л за день",
        marginBalance: "Маржинальный баланс",
        balance: "Баланс",
        profit: "Прибыль ($)",
    },
    de: {
        benchmarkBTC: "Benchmark BTC",
        return: "Rendite (%)",
        realizedReturn: "Realisierte Rendite",
        plByDay: "P\\L pro Tag",
        marginBalance: "Margenbilanz",
        balance: "Saldo",
        profit: "Gewinn ($)",
    },
    es: {
        benchmarkBTC: "BTC de Referencia",
        return: "Retorno (%)",
        realizedReturn: "Retorno Realizado",
        plByDay: "P\\L por día",
        marginBalance: "Balance de Margen",
        balance: "Saldo",
        profit: "Ganancia ($)",
    },
};

export const drawDown = {
    drawdown: {
        en: "DrawDown:",
        ru: "Максимальная просадка:",
        de: "Maximaler Rückgang:",
        es: "Pérdida máxima:",
    },
    drawdownDuration: {
        en: "DrawDown Duration:",
        ru: "Длительность просадки:",
        de: "Dauer des Rückgangs:",
        es: "Duración de la pérdida:",
    },
    revenueLabels: {
        en: "Revenue by month (%)",
        ru: "Доход по месяцам (%)",
        de: "Umsatz pro Monat (%)",
        es: "Ingresos por mes (%)",
    },
    plByMonthLabels: {
        en: "P/L by month:",
        ru: "Прибыль/Убыток за месяц:",
        de: "Gewinn/Verlust pro Monat:",
        es: "Ganancias/Pérdidas por mes:",
    }
};






//my card 
// =================
export const translationsInfo = {
    accountInformation: {
        en: "Account Information",
        ru: "Информация об аккаунте",
        de: "Kontoinformationen",
        es: "Información de la cuenta",
    },
    balanceAnalytics: {
        en: "Balance Analytics",
        ru: "Аналитика баланса",
        de: "Bilanzanalyse",
        es: "Análisis de balance",
    },
    profitNet: {
        en: "Profit Net",
        ru: "Чистая прибыль",
        de: "Reingewinn",
        es: "Ganancia neta",
    },
    funding: {
        en: "Funding",
        ru: "Финансирование",
        de: "Finanzierung",
        es: "Financiación",
    },
    profitRatio: {
        en: "Profit Ratio",
        ru: "Коэффициент прибыли",
        de: "Gewinnverhältnis",
        es: "Proporción de ganancias",
    },
    winRatio: {
        en: "Win Ratio",
        ru: "Коэффициент выигрыша",
        de: "Gewinnquote",
        es: "Proporción de victorias",
    },
    commission: {
        en: "Commission",
        ru: "Комиссия",
        de: "Kommission",
        es: "Comisión",
    },
    additionalInformation: {
        en: "Additional Information",
        ru: "Дополнительная информация",
        de: "Zusätzliche Informationen",
        es: "Información adicional",
    },
    DWinformation: {
        en: "D/W Information",
        ru: "Информация о депозитах и снятиях",
        de: "Ein-/Auszahlungsinformationen",
        es: "Información de depósitos y retiros",
    },
};






// Tarjimalar obyekti
export const languagesLab = {
    en: {
        totalProfitOf: "The sum of total profit and total loss",
        accountInformation: "Account Information",
        balanceAnalytics: "Balance Analytics",
        profitNet: "Net Profit",
        funding: "Funding",
        profitRatio: "Profit Ratio",
        winRatio: "Win Ratio",
        commission: "Commission",
        additionalInformation: "Additional Information",
        DWinformation: "Deposit and Withdrawal Information",

        trackingDays: "Tracking days",
        totalDays: "Total days",
        startDate: "Start date",
        averageBalance: "Average balance",
        maxBalance: "Maximum balance",
        minBalance: "Minimum balance",
        totalProfit: "Total profit",
        totalLoss: "Total loss",
        net: "Net",
        received: "Received",
        paid: "Paid",
        pnl: "P/L ratio",
        averageProfit: "Average profit",
        averageLoss: "Average loss",
        winningDays: "Winning days",
        losingDays: "Losing days",
        breakevenDays: "Breakeven days",
        total: "Total",
        rebate: "Rebate",
        tradeVolume: "Trade volume",
        marketsUsed: "Markets used",
        totalTrades: "Total trades",
        totalDeposit: "Total deposit",
        totalWithdrawal: "Total withdrawal",
        referralPayments: "Referral payments",
    },
    ru: {
        totalProfitOf: "Сумма общей прибыли и общего убытка",
        accountInformation: "Информация об аккаунте",
        balanceAnalytics: "Аналитика баланса",
        profitNet: "Чистая прибыль",
        funding: "Финансирование",
        profitRatio: "Соотношение прибыли",
        winRatio: "Коэффициент выигрыша",
        commission: "Комиссия",
        additionalInformation: "Дополнительная информация",
        DWinformation: "Информация о депозите и снятии",
        trackingDays: "Дни отслеживания",
        totalDays: "Общее количество дней",
        startDate: "Дата начала",
        averageBalance: "Средний баланс",
        maxBalance: "Максимальный баланс",
        minBalance: "Минимальный баланс",
        totalProfit: "Общая прибыль",
        totalLoss: "Общие убытки",
        net: "Чистая сумма",
        received: "Получено",
        paid: "Оплачено",
        pnl: "Соотношение прибыли/убытков",
        averageProfit: "Средняя прибыль",
        averageLoss: "Средний убыток",
        winningDays: "Дни выигрыша",
        losingDays: "Дни проигрыша",
        breakevenDays: "Дни безубыточности",
        total: "Всего",
        rebate: "Возврат",
        tradeVolume: "Объем торговли",
        marketsUsed: "Используемые рынки",
        totalTrades: "Общее количество сделок",
        totalDeposit: "Общая сумма депозита",
        totalWithdrawal: "Общая сумма снятия",
        referralPayments: "Реферальные выплаты",
    },
    de: {
        totalProfitOf: "Die Summe von Gesamtgewinn und Gesamtverlust",
        accountInformation: "Kontoinformation",
        balanceAnalytics: "Bilanzanalyse",
        profitNet: "Netto Gewinn",
        funding: "Finanzierung",
        profitRatio: "Gewinnverhältnis",
        winRatio: "Gewinnquote",
        commission: "Provision",
        additionalInformation: "Zusätzliche Informationen",
        DWinformation: "Einzahlungs- und Abhebungsinformationen",
        trackingDays: "Verfolgungstage",
        totalDays: "Gesamttage",
        startDate: "Startdatum",
        averageBalance: "Durchschnittliches Guthaben",
        maxBalance: "Maximales Guthaben",
        minBalance: "Minimales Guthaben",
        totalProfit: "Gesamtgewinn",
        totalLoss: "Gesamtverlust",
        net: "Netto",
        received: "Erhalten",
        paid: "Bezahlt",
        pnl: "Gewinn/Verlust-Verhältnis",
        averageProfit: "Durchschnittlicher Gewinn",
        averageLoss: "Durchschnittlicher Verlust",
        winningDays: "Gewinntage",
        losingDays: "Verlusttage",
        breakevenDays: "Tage ohne Verlust",
        total: "Gesamt",
        rebate: "Rückzahlung",
        tradeVolume: "Handelsvolumen",
        marketsUsed: "Verwendete Märkte",
        totalTrades: "Gesamte Handelsgeschäfte",
        totalDeposit: "Gesamteinzahlung",
        totalWithdrawal: "Gesamtabhebung",
        referralPayments: "Empfehlungszahlungen",
    },
    es: {
        totalProfitOf: "La suma del beneficio total y la pérdida total",
        accountInformation: "Información de la cuenta",
        balanceAnalytics: "Análisis del saldo",
        profitNet: "Beneficio Neto",
        funding: "Financiación",
        profitRatio: "Proporción de beneficios",
        winRatio: "Índice de ganancia",
        commission: "Comisión",
        additionalInformation: "Información adicional",
        DWinformation: "Información sobre depósitos y retiros",
        trackingDays: "Días de seguimiento",
        totalDays: "Días totales",
        startDate: "Fecha de inicio",
        averageBalance: "Saldo promedio",
        maxBalance: "Saldo máximo",
        minBalance: "Saldo mínimo",
        totalProfit: "Beneficio total",
        totalLoss: "Pérdida total",
        net: "Neto",
        received: "Recibido",
        paid: "Pagado",
        pnl: "Relación P/G",
        averageProfit: "Ganancia promedio",
        averageLoss: "Pérdida promedio",
        winningDays: "Días de ganancia",
        losingDays: "Días de pérdida",
        breakevenDays: "Días de equilibrio",
        total: "Total",
        rebate: "Reembolso",
        tradeVolume: "Volumen de comercio",
        marketsUsed: "Mercados usados",
        totalTrades: "Operaciones totales",
        totalDeposit: "Depósito total",
        totalWithdrawal: "Retiro total",
        referralPayments: "Pagos por referencias",
    },
};

// Tarjimalar obyekti
export const languagesTool = {
    en: {
        accountInformation: "Detailed information about the account, including its activity and key metrics.",
        balanceAnalytics: "Insights and analysis of the account's balance over time, highlighting trends and key changes.",
        profitNet: "The net profit earned after deducting all expenses and losses from the total revenue.",
        funding: "Information about financial support or contributions made to the account.",
        profitRatio: "The percentage that represents the account's profitability relative to its expenses or losses.",
        winRatio: "The ratio of successful outcomes (e.g., profitable trades) to the total number of outcomes.",
        commission: "The fees or charges deducted for facilitating transactions or services within the account.",
        additionalInformation: "Supplementary details that provide further context or insights about the account's activities.",
        DWinformation: "Comprehensive data on deposits and withdrawals, including their amounts and dates.",
    },
    ru: {
        accountInformation: "Подробная информация об аккаунте, включая его активность и ключевые показатели.",
        balanceAnalytics: "Анализ баланса аккаунта за определенный период, с выделением тенденций и изменений.",
        profitNet: "Чистая прибыль, заработанная после вычета всех расходов и убытков из общего дохода.",
        funding: "Информация о финансовой поддержке или взносах, внесенных на аккаунт.",
        profitRatio: "Процент, отражающий прибыльность аккаунта по отношению к его расходам или убыткам.",
        winRatio: "Соотношение успешных операций (например, прибыльных сделок) к общему числу операций.",
        commission: "Комиссионные сборы или платежи за оказание услуг или проведение транзакций в аккаунте.",
        additionalInformation: "Дополнительная информация, предоставляющая контекст или инсайты о действиях аккаунта.",
        DWinformation: "Полные данные о депозитах и снятиях, включая суммы и даты.",
    },
    de: {
        accountInformation: "Detaillierte Informationen über das Konto, einschließlich seiner Aktivitäten und wichtigsten Kennzahlen.",
        balanceAnalytics: "Einblicke und Analysen des Kontostands über einen bestimmten Zeitraum, mit Trends und Änderungen.",
        profitNet: "Der Nettogewinn, der nach Abzug aller Ausgaben und Verluste aus den Gesamteinnahmen erzielt wurde.",
        funding: "Informationen über finanzielle Unterstützung oder Einzahlungen auf das Konto.",
        profitRatio: "Der Prozentsatz, der die Rentabilität des Kontos im Verhältnis zu den Ausgaben oder Verlusten darstellt.",
        winRatio: "Das Verhältnis erfolgreicher Ergebnisse (z. B. profitabler Trades) zur Gesamtanzahl der Ergebnisse.",
        commission: "Die Gebühren oder Kosten, die für die Durchführung von Transaktionen oder Dienstleistungen im Konto anfallen.",
        additionalInformation: "Zusätzliche Informationen, die weitere Einblicke oder Kontext zu den Aktivitäten des Kontos bieten.",
        DWinformation: "Umfassende Daten zu Einzahlungen und Abhebungen, einschließlich ihrer Beträge und Daten.",
    },
    es: {
        accountInformation: "Información detallada sobre la cuenta, incluyendo su actividad y métricas clave.",
        balanceAnalytics: "Análisis e información sobre el saldo de la cuenta a lo largo del tiempo, destacando tendencias y cambios clave.",
        profitNet: "El beneficio neto obtenido después de deducir todos los gastos y pérdidas de los ingresos totales.",
        funding: "Información sobre el apoyo financiero o contribuciones realizadas a la cuenta.",
        profitRatio: "El porcentaje que representa la rentabilidad de la cuenta en relación con sus gastos o pérdidas.",
        winRatio: "La proporción de resultados exitosos (por ejemplo, transacciones rentables) respecto al número total de resultados.",
        commission: "Las tarifas o cargos deducidos por facilitar transacciones o servicios dentro de la cuenta.",
        additionalInformation: "Detalles adicionales que proporcionan contexto o información sobre las actividades de la cuenta.",
        DWinformation: "Datos completos sobre depósitos y retiros, incluyendo sus montos y fechas.",
    },
};


// ====================
export const tooltipTextLab = {
    en: {
        trackingDays: "The number of days the account has been actively tracked.",
        totalDays: "The total number of days for which the account is considered.",
        startDate: "The date when the account started.",
        averageBalance: "The average balance of the account over the period.",
        maximumBalance: "The highest balance ever recorded in the account.",
        minimumBalance: "The lowest balance ever recorded in the account.",
        theSumOfTotal: "The total sum of profit and loss for the account.",
        totalProfit: "The total profit earned by the account.",
        totalLoss: "The total loss incurred by the account.",
        Net: "The net value of the account (received - paid).",
        Received: "The total amount received by the account.",
        Paid: "The total amount paid from the account.",
        PLratio: "The ratio of profit to loss in the account.",
        averageProfit: "The average percentage of profit over the period.",
        averageLoss: "The average percentage of loss over the period.",
        WinningDays: "The number of days with a positive balance.",
        losingDays: "The number of days with a negative balance.",
        breakevenDays: "The number of days the account broke even.",
        total: "The total amount of commission in the account.",
        rebate: "The rebate amount received by the account.",
        tradeVolume: "The total volume of trades conducted in the account.",
        marketsUsed: "The number of different markets used in trading.",
        totalTrades: "The total number of trades conducted in the account.",
        totalDeposit: "The total amount deposited into the account.",
        totalWithdrawal: "The total amount withdrawn from the account.",
        referralPayments: "The total payments made for referrals.",
    },
    ru: {
        trackingDays: "Количество дней, в течение которых учетная запись активно отслеживалась.",
        totalDays: "Общее количество дней, за которые учитывается учетная запись.",
        startDate: "Дата начала работы учетной записи.",
        averageBalance: "Средний баланс учетной записи за период.",
        maximumBalance: "Максимальный зарегистрированный баланс учетной записи.",
        minimumBalance: "Минимальный зарегистрированный баланс учетной записи.",
        theSumOfTotal: "Общая сумма прибыли и убытков учетной записи.",
        totalProfit: "Общая прибыль, полученная учетной записью.",
        totalLoss: "Общий убыток, понесенный учетной записью.",
        Net: "Чистая стоимость учетной записи (получено - выплачено).",
        Received: "Общая сумма, полученная учетной записью.",
        Paid: "Общая сумма, выплаченная с учетной записи.",
        PLratio: "Соотношение прибыли к убыткам в учетной записи.",
        averageProfit: "Средний процент прибыли за период.",
        averageLoss: "Средний процент убытков за период.",
        WinningDays: "Количество дней с положительным балансом.",
        losingDays: "Количество дней с отрицательным балансом.",
        breakevenDays: "Количество дней, когда учетная запись не принесла ни прибыли, ни убытков.",
        total: "Общая сумма комиссий в учетной записи.",
        rebate: "Сумма возврата, полученная учетной записью.",
        tradeVolume: "Общий объем сделок, проведенных учетной записью.",
        marketsUsed: "Количество различных рынков, использованных для торговли.",
        totalTrades: "Общее количество сделок, проведенных учетной записью.",
        totalDeposit: "Общая сумма депозитов на учетной записи.",
        totalWithdrawal: "Общая сумма снятий с учетной записи.",
        referralPayments: "Общие выплаты за рефералов.",
    },
    de: {
        trackingDays: "Die Anzahl der Tage, an denen das Konto aktiv verfolgt wurde.",
        totalDays: "Die Gesamtzahl der Tage, für die das Konto berücksichtigt wird.",
        startDate: "Das Datum, an dem das Konto gestartet wurde.",
        averageBalance: "Der durchschnittliche Kontostand über den Zeitraum.",
        maximumBalance: "Der höchste jemals aufgezeichnete Kontostand.",
        minimumBalance: "Der niedrigste jemals aufgezeichnete Kontostand.",
        theSumOfTotal: "Die Gesamtsumme von Gewinn und Verlust des Kontos.",
        totalProfit: "Der Gesamtertrag des Kontos.",
        totalLoss: "Der Gesamtverlust des Kontos.",
        Net: "Der Nettowert des Kontos (erhalten - bezahlt).",
        Received: "Der Gesamtbetrag, der auf dem Konto eingegangen ist.",
        Paid: "Der Gesamtbetrag, der vom Konto bezahlt wurde.",
        PLratio: "Das Verhältnis von Gewinn zu Verlust auf dem Konto.",
        averageProfit: "Der durchschnittliche Prozentsatz des Gewinns über den Zeitraum.",
        averageLoss: "Der durchschnittliche Prozentsatz des Verlustes über den Zeitraum.",
        WinningDays: "Die Anzahl der Tage mit positivem Saldo.",
        losingDays: "Die Anzahl der Tage mit negativem Saldo.",
        breakevenDays: "Die Anzahl der Tage, an denen das Konto ausgeglichen war.",
        total: "Die Gesamtsumme der Provision auf dem Konto.",
        rebate: "Der Rückerstattungsbetrag, der auf dem Konto eingegangen ist.",
        tradeVolume: "Das gesamte Handelsvolumen des Kontos.",
        marketsUsed: "Die Anzahl der verschiedenen Märkte, die gehandelt wurden.",
        totalTrades: "Die Gesamtanzahl der durchgeführten Trades.",
        totalDeposit: "Der Gesamtbetrag, der auf das Konto eingezahlt wurde.",
        totalWithdrawal: "Der Gesamtbetrag, der vom Konto abgehoben wurde.",
        referralPayments: "Die gesamten Zahlungen für Empfehlungen.",
    },
    es: {
        trackingDays: "El número de días que la cuenta ha sido activamente monitoreada.",
        totalDays: "El número total de días considerados para la cuenta.",
        startDate: "La fecha de inicio de la cuenta.",
        averageBalance: "El saldo promedio de la cuenta durante el período.",
        maximumBalance: "El saldo más alto registrado en la cuenta.",
        minimumBalance: "El saldo más bajo registrado en la cuenta.",
        theSumOfTotal: "La suma total de ganancias y pérdidas de la cuenta.",
        totalProfit: "El beneficio total obtenido por la cuenta.",
        totalLoss: "La pérdida total incurrida por la cuenta.",
        Net: "El valor neto de la cuenta (recibido - pagado).",
        Received: "El monto total recibido por la cuenta.",
        Paid: "El monto total pagado desde la cuenta.",
        PLratio: "La relación de ganancias y pérdidas en la cuenta.",
        averageProfit: "El porcentaje promedio de ganancias durante el período.",
        averageLoss: "El porcentaje promedio de pérdidas durante el período.",
        WinningDays: "El número de días con saldo positivo.",
        losingDays: "El número de días con saldo negativo.",
        breakevenDays: "El número de días en que la cuenta quedó en equilibrio.",
        total: "La cantidad total de comisiones en la cuenta.",
        rebate: "El monto del reembolso recibido por la cuenta.",
        tradeVolume: "El volumen total de operaciones realizadas en la cuenta.",
        marketsUsed: "El número de mercados diferentes utilizados para operar.",
        totalTrades: "El número total de operaciones realizadas en la cuenta.",
        totalDeposit: "El monto total depositado en la cuenta.",
        totalWithdrawal: "El monto total retirado de la cuenta.",
        referralPayments: "Los pagos totales realizados por referidos.",
    },
};


