export const translations = {
    en: {
        lite: "Lite",
        little: "A little",
        hour: "Hour",
        day: "Day",
        week: "Week",
        kIndicators: "Key indicators",
        main: "Main",
        investment: "Investment",
        trades: "Trades",
        views: "views",
    },
    ru: {
        lite: "Лёгкий",
        little: "Немного",
        hour: "Час",
        day: "День",
        week: "Неделя",
        kIndicators: "Ключевые показатели",
        main: "Главная",
        investment: "Инвестиции",
        trades: "Сделки",
        views: "просмотры",
    },
    es: {
        lite: "Ligero",
        little: "Un poco",
        hour: "Hora",
        day: "Día",
        week: "Semana",
        kIndicators: "Indicadores clave",
        main: "Principal",
        investment: "Inversión",
        trades: "Comercios",
        views: "vistas",
    },
    de: {
        lite: "Leicht",
        little: "Ein wenig",
        hour: "Stunde",
        day: "Tag",
        week: "Woche",
        kIndicators: "Schlüsselindikatoren",
        main: "Haupt",
        investment: "Investition",
        trades: "Handel",
        views: "Ansichten"
    },
};

export const checkboxData = [
    {
        key: "benchmarkBTC",
        label: {
            en: "Benchmark BTC",
            ru: "Бенчмарк BTC",
            es: "Referencia BTC",
            de: "Benchmark BTC"
        },
        color: "#FFD700"
    },
    {
        key: "return",
        label: {
            en: "Return (%)",
            ru: "Доходность (%)",
            es: "Retorno (%)",
            de: "Rendite (%)"
        },
        color: "#FFA500"
    },
    {
        key: "realizedReturn",
        label: {
            en: "Realized Return",
            ru: "Реализованный доход",
            es: "Retorno realizado",
            de: "Realisierte Rendite"
        },
        color: "#1E90FF"
    },
    {
        key: "marginBalance",
        label: {
            en: "Margin Balance",
            ru: "Маржинальный баланс",
            es: "Saldo de margen",
            de: "Margenguthaben"
        },
        color: "#3CB371"
    },
    {
        key: "balance",
        label: {
            en: "Balance",
            ru: "Баланс",
            es: "Saldo",
            de: "Guthaben"
        },
        color: "#A52A2A"
    },
    {
        key: "plByday",
        label: {
            en: "P\\L by day",
            ru: "Прибыль/Убыток за день",
            es: "P\\L por día",
            de: "P\\L pro Tag"
        },
        color: "#20B2AA"
    },
    {
        key: "profit",
        label: {
            en: "Profit ($)",
            ru: "Прибыль ($)",
            es: "Beneficio ($)",
            de: "Gewinn ($)"
        },
        color: "#4B0082"
    },
    {
        key: "usedLeverage",
        label: {
            en: "Used Leverage",
            ru: "Используемое плечо",
            es: "Apalancamiento utilizado",
            de: "Genutzter Hebel"
        },
        color: "#9370DB"
    },
    {
        key: "drawDown",
        label: {
            en: "DrawDown",
            ru: "Просадка",
            es: "Pérdida máxima",
            de: "Maximaler Verlust"
        },
        color: "#4169E1"
    },
    {
        key: "drawDownDuration",
        label: {
            en: "DrawDown Duration",
            ru: "Длительность просадки",
            es: "Duración de la pérdida",
            de: "Verlustdauer"
        },
        color: "#1E90FF"
    },
];

export const transInvestment = {
    en: {
        lifetimeExperience: "Lifetime Experience",
        sharpeRatio: "Sharpe Ratio",
        calmarRatio: "Calmar Ratio",
        sortinoRatio: "Sortino Ratio",
        ir: "IR",
        volatility: "Volatility",
        alphaRatio: "α Ratio",
        betaRatio: "β Ratio",
        treynorRatio: "Treynor Ratio",
        schwagerRatio: "Schwager Ratio",
        rSquared: "R²",
        mSquared: "M²",
        lifetimeExperienceDescription: "Very good",
        sharpeRatioDescription: "Excellent risk-adjusted performance",
        calmarRatioDescription: "High return per drawdown risk",
        sortinoRatioDescription: "Excellent downside risk-adjusted performance",
        irDescription: "Greatly outperforms benchmark",
        volatilityDescription: "Some fluctuations, moderate risk",
        alphaRatioDescription: "Greatly outperforms benchmark",
        betaRatioDescription: "Moves with market",
        treynorRatioDescription: "High return per market risk",
        schwagerRatioDescription: "Favorable balance of returns",
        rSquaredDescription: "Independent from benchmark",
        mSquaredDescription: "Significant risk-adjusted outperformance",
    },
    uz: {
        lifetimeExperience: "Umr bo'yi tajriba",
        sharpeRatio: "Sharpe nisbat",
        calmarRatio: "Calmar nisbat",
        sortinoRatio: "Sortino nisbat",
        ir: "IR",
        volatility: "Volatillik",
        alphaRatio: "α nisbat",
        betaRatio: "β nisbat",
        treynorRatio: "Treynor nisbat",
        schwagerRatio: "Schwager nisbat",
        rSquared: "R²",
        mSquared: "M²",
        lifetimeExperienceDescription: "Juda yaxshi",
        sharpeRatioDescription: "Yaxshi risk-adjusted ko'rsatkich",
        calmarRatioDescription: "Yuqori daromad, kichik xatarlik",
        sortinoRatioDescription: "Yuqori pastga qarab risk-adjusted ko'rsatkich",
        irDescription: "Benchmarkdan ancha yuqori ko'rsatkich",
        volatilityDescription: "Ba'zi o'zgarishlar, o'rtacha risk",
        alphaRatioDescription: "Benchmarkdan ancha yuqori ko'rsatkich",
        betaRatioDescription: "Bozor bilan harakat qiladi",
        treynorRatioDescription: "Bozor riskiga nisbatan yuqori daromad",
        schwagerRatioDescription: "Daromadlarning yaxshi balanslanganligi",
        rSquaredDescription: "Benchmarkdan mustaqil",
        mSquaredDescription: "Katta risk-adjusted daromad",
    },
    ru: {
        lifetimeExperience: "Опыт всей жизни",
        sharpeRatio: "Коэффициент Шарпа",
        calmarRatio: "Коэффициент Калмара",
        sortinoRatio: "Коэффициент Сортино",
        ir: "IR",
        volatility: "Волатильность",
        alphaRatio: "α коэффициент",
        betaRatio: "β коэффициент",
        treynorRatio: "Коэффициент Трейнора",
        schwagerRatio: "Коэффициент Швагера",
        rSquared: "R²",
        mSquared: "M²",
        lifetimeExperienceDescription: "Очень хорошо",
        sharpeRatioDescription: "Отличная производительность с учетом риска",
        calmarRatioDescription: "Высокая доходность при риске просадки",
        sortinoRatioDescription: "Отличная производительность с учетом риска вниз",
        irDescription: "Значительно превосходит эталон",
        volatilityDescription: "Некоторые колебания, умеренный риск",
        alphaRatioDescription: "Значительно превосходит эталон",
        betaRatioDescription: "Двигается с рынком",
        treynorRatioDescription: "Высокая доходность при рыночном риске",
        schwagerRatioDescription: "Благоприятный баланс доходности",
        rSquaredDescription: "Независим от эталона",
        mSquaredDescription: "Значительная доходность с учетом риска",
    },
    es: {
        lifetimeExperience: "Experiencia de toda la vida",
        sharpeRatio: "Índice de Sharpe",
        calmarRatio: "Índice de Calmar",
        sortinoRatio: "Índice de Sortino",
        ir: "IR",
        volatility: "Volatilidad",
        alphaRatio: "α Índice",
        betaRatio: "β Índice",
        treynorRatio: "Índice de Treynor",
        schwagerRatio: "Índice de Schwager",
        rSquared: "R²",
        mSquared: "M²",
        lifetimeExperienceDescription: "Muy bueno",
        sharpeRatioDescription: "Excelente rendimiento ajustado al riesgo",
        calmarRatioDescription: "Alta rentabilidad por riesgo de retroceso",
        sortinoRatioDescription: "Excelente rendimiento ajustado al riesgo a la baja",
        irDescription: "Supera significativamente el benchmark",
        volatilityDescription: "Algunas fluctuaciones, riesgo moderado",
        alphaRatioDescription: "Supera significativamente el benchmark",
        betaRatioDescription: "Se mueve con el mercado",
        treynorRatioDescription: "Alta rentabilidad por riesgo de mercado",
        schwagerRatioDescription: "Balance favorable de rendimientos",
        rSquaredDescription: "Independiente del benchmark",
        mSquaredDescription: "Supera significativamente el benchmark ajustado al riesgo",
    },
    de: {
        lifetimeExperience: "Lebenslange Erfahrung",
        sharpeRatio: "Sharpe-Verhältnis",
        calmarRatio: "Calmar-Verhältnis",
        sortinoRatio: "Sortino-Verhältnis",
        ir: "IR",
        volatility: "Volatilität",
        alphaRatio: "α Verhältnis",
        betaRatio: "β Verhältnis",
        treynorRatio: "Treynor-Verhältnis",
        schwagerRatio: "Schwager-Verhältnis",
        rSquared: "R²",
        mSquared: "M²",
        lifetimeExperienceDescription: "Sehr gut",
        sharpeRatioDescription: "Ausgezeichnete risikoadjustierte Leistung",
        calmarRatioDescription: "Hohe Rendite pro Rückschlagrisiko",
        sortinoRatioDescription: "Ausgezeichnete Leistung bei nach unten gerichteten Risiken",
        irDescription: "Übertrifft das Benchmark erheblich",
        volatilityDescription: "Einige Schwankungen, moderates Risiko",
        alphaRatioDescription: "Übertrifft das Benchmark erheblich",
        betaRatioDescription: "Bewegt sich mit dem Markt",
        treynorRatioDescription: "Hohe Rendite pro Marktrisiko",
        schwagerRatioDescription: "Günstige Balance der Renditen",
        rSquaredDescription: "Unabhängig vom Benchmark",
        mSquaredDescription: "Erheblicher risikoadjustierter Mehrwert",
    }
};

export const labelsBar = {
    usedLeverage: {
        en: "Used Leverage:",
        ru: "Используемое кредитное плечо:",
        de: "Verwendeter Hebel:",
        es: "Apalancamiento usado:",
    },
    longPositions: {
        en: "Long positions:",
        ru: "Длинные позиции:",
        de: "Long-Positionen:",
        es: "Posiciones largas:",
    },
    shortPositions: {
        en: "Short positions:",
        ru: "Короткие позиции:",
        de: "Short-Positionen:",
        es: "Posiciones cortas:",
    },
};

export const labels = {
    en: {
        benchmarkBTC: "Benchmark BTC",
        return: "Return (%)",
        realizedReturn: "Realized Return",
        plByDay: "P\\L by day",
        marginBalance: "Margin Balance",
        balance: "Balance",
        profit: "Profit ($)",
    },
    ru: {
        benchmarkBTC: "Бенчмарк BTC",
        return: "Доходность (%)",
        realizedReturn: "Реализованная доходность",
        plByDay: "П\\Л за день",
        marginBalance: "Маржинальный баланс",
        balance: "Баланс",
        profit: "Прибыль ($)",
    },
    de: {
        benchmarkBTC: "Benchmark BTC",
        return: "Rendite (%)",
        realizedReturn: "Realisierte Rendite",
        plByDay: "P\\L pro Tag",
        marginBalance: "Margenbilanz",
        balance: "Saldo",
        profit: "Gewinn ($)",
    },
    es: {
        benchmarkBTC: "BTC de Referencia",
        return: "Retorno (%)",
        realizedReturn: "Retorno Realizado",
        plByDay: "P\\L por día",
        marginBalance: "Balance de Margen",
        balance: "Saldo",
        profit: "Ganancia ($)",
    },
};

export const drawDown = {
    drawdown: {
        en: "DrawDown:",
        ru: "Максимальная просадка:",
        de: "Maximaler Rückgang:",
        es: "Pérdida máxima:",
    },
    drawdownDuration: {
        en: "DrawDown Duration:",
        ru: "Длительность просадки:",
        de: "Dauer des Rückgangs:",
        es: "Duración de la pérdida:",
    },
    revenueLabels: {
        en: "Revenue by month (%)",
        ru: "Доход по месяцам (%)",
        de: "Umsatz pro Monat (%)",
        es: "Ingresos por mes (%)",
    },
    plByMonthLabels: {
        en: "P/L by month:",
        ru: "Прибыль/Убыток за месяц:",
        de: "Gewinn/Verlust pro Monat:",
        es: "Ganancias/Pérdidas por mes:",
    }
};






//my card 
// =================
export const translationsInfo = {
    accountInformation: {
        en: "Account Information",
        ru: "Информация об аккаунте",
        de: "Kontoinformationen",
        es: "Información de la cuenta",
    },
    balanceAnalytics: {
        en: "Balance Analytics",
        ru: "Аналитика баланса",
        de: "Bilanzanalyse",
        es: "Análisis de balance",
    },
    profitNet: {
        en: "Profit Net",
        ru: "Чистая прибыль",
        de: "Reingewinn",
        es: "Ganancia neta",
    },
    funding: {
        en: "Funding",
        ru: "Финансирование",
        de: "Finanzierung",
        es: "Financiación",
    },
    profitRatio: {
        en: "Profit Ratio",
        ru: "Коэффициент прибыли",
        de: "Gewinnverhältnis",
        es: "Proporción de ganancias",
    },
    winRatio: {
        en: "Win Ratio",
        ru: "Коэффициент выигрыша",
        de: "Gewinnquote",
        es: "Proporción de victorias",
    },
    commission: {
        en: "Commission",
        ru: "Комиссия",
        de: "Kommission",
        es: "Comisión",
    },
    additionalInformation: {
        en: "Additional Information",
        ru: "Дополнительная информация",
        de: "Zusätzliche Informationen",
        es: "Información adicional",
    },
    DWinformation: {
        en: "D/W Information",
        ru: "Информация о депозитах и снятиях",
        de: "Ein-/Auszahlungsinformationen",
        es: "Información de depósitos y retiros",
    },
};






// Tarjimalar obyekti
export const languagesLab = {
    en: {
        totalProfitOf: "The sum of total profit and total loss",
        trackingDays: "Tracking days",
        totalDays: "Total days",
        startDate: "Start date",
        averageBalance: "Average balance",
        maxBalance: "Maximum balance",
        minBalance: "Minimum balance",
        totalProfit: "Total profit",
        totalLoss: "Total loss",
        net: "Net",
        received: "Received",
        paid: "Paid",
        pnl: "P/L ratio",
        averageProfit: "Average profit",
        averageLoss: "Average loss",
        winningDays: "Winning days",
        losingDays: "Losing days",
        breakevenDays: "Breakeven days",
        total: "Total",
        rebate: "Rebate",
        tradeVolume: "Trade volume",
        marketsUsed: "Markets used",
        totalTrades: "Total trades",
        totalDeposit: "Total deposit",
        totalWithdrawal: "Total withdrawal",
        referralPayments: "Referral payments",
    },
    ru: {
        totalProfitOf: "Сумма общей прибыли и общего убытка",
        accountInformation: "Информация об аккаунте",
        balanceAnalytics: "Аналитика баланса",
        profitNet: "Чистая прибыль",
        funding: "Финансирование",
        profitRatio: "Соотношение прибыли",
        winRatio: "Коэффициент выигрыша",
        commission: "Комиссия",
        additionalInformation: "Дополнительная информация",
        DWinformation: "Информация о депозите и снятии",
        trackingDays: "Дни отслеживания",
        totalDays: "Общее количество дней",
        startDate: "Дата начала",
        averageBalance: "Средний баланс",
        maxBalance: "Максимальный баланс",
        minBalance: "Минимальный баланс",
        totalProfit: "Общая прибыль",
        totalLoss: "Общие убытки",
        net: "Чистая сумма",
        received: "Получено",
        paid: "Оплачено",
        pnl: "Соотношение прибыли/убытков",
        averageProfit: "Средняя прибыль",
        averageLoss: "Средний убыток",
        winningDays: "Дни выигрыша",
        losingDays: "Дни проигрыша",
        breakevenDays: "Дни безубыточности",
        total: "Всего",
        rebate: "Возврат",
        tradeVolume: "Объем торговли",
        marketsUsed: "Используемые рынки",
        totalTrades: "Общее количество сделок",
        totalDeposit: "Общая сумма депозита",
        totalWithdrawal: "Общая сумма снятия",
        referralPayments: "Реферальные выплаты",
    },
    de: {
        totalProfitOf: "Die Summe von Gesamtgewinn und Gesamtverlust",
        accountInformation: "Kontoinformation",
        balanceAnalytics: "Bilanzanalyse",
        profitNet: "Netto Gewinn",
        funding: "Finanzierung",
        profitRatio: "Gewinnverhältnis",
        winRatio: "Gewinnquote",
        commission: "Provision",
        additionalInformation: "Zusätzliche Informationen",
        DWinformation: "Einzahlungs- und Abhebungsinformationen",
        trackingDays: "Verfolgungstage",
        totalDays: "Gesamttage",
        startDate: "Startdatum",
        averageBalance: "Durchschnittliches Guthaben",
        maxBalance: "Maximales Guthaben",
        minBalance: "Minimales Guthaben",
        totalProfit: "Gesamtgewinn",
        totalLoss: "Gesamtverlust",
        net: "Netto",
        received: "Erhalten",
        paid: "Bezahlt",
        pnl: "Gewinn/Verlust-Verhältnis",
        averageProfit: "Durchschnittlicher Gewinn",
        averageLoss: "Durchschnittlicher Verlust",
        winningDays: "Gewinntage",
        losingDays: "Verlusttage",
        breakevenDays: "Tage ohne Verlust",
        total: "Gesamt",
        rebate: "Rückzahlung",
        tradeVolume: "Handelsvolumen",
        marketsUsed: "Verwendete Märkte",
        totalTrades: "Gesamte Handelsgeschäfte",
        totalDeposit: "Gesamteinzahlung",
        totalWithdrawal: "Gesamtabhebung",
        referralPayments: "Empfehlungszahlungen",
    },
    es: {
        totalProfitOf: "La suma del beneficio total y la pérdida total",
        accountInformation: "Información de la cuenta",
        balanceAnalytics: "Análisis del saldo",
        profitNet: "Beneficio Neto",
        funding: "Financiación",
        profitRatio: "Proporción de beneficios",
        winRatio: "Índice de ganancia",
        commission: "Comisión",
        additionalInformation: "Información adicional",
        DWinformation: "Información sobre depósitos y retiros",
        trackingDays: "Días de seguimiento",
        totalDays: "Días totales",
        startDate: "Fecha de inicio",
        averageBalance: "Saldo promedio",
        maxBalance: "Saldo máximo",
        minBalance: "Saldo mínimo",
        totalProfit: "Beneficio total",
        totalLoss: "Pérdida total",
        net: "Neto",
        received: "Recibido",
        paid: "Pagado",
        pnl: "Relación P/G",
        averageProfit: "Ganancia promedio",
        averageLoss: "Pérdida promedio",
        winningDays: "Días de ganancia",
        losingDays: "Días de pérdida",
        breakevenDays: "Días de equilibrio",
        total: "Total",
        rebate: "Reembolso",
        tradeVolume: "Volumen de comercio",
        marketsUsed: "Mercados usados",
        totalTrades: "Operaciones totales",
        totalDeposit: "Depósito total",
        totalWithdrawal: "Retiro total",
        referralPayments: "Pagos por referencias",
    },
};



// ====================
export const tooltipTextLab = {
    en: {
        "Tracking days": "The number of days the account has been actively tracked.",
        "Total days": "The total number of days for which the account is considered.",
        "Start date": "The date when the account started.",
        "Average balance": "The average balance of the account over the period.",
        "Maximum balance": "The highest balance ever recorded in the account.",
        "Minimum balance": "The lowest balance ever recorded in the account.",
        "The sum of total profit and total loss": "The total sum of profit and loss for the account.",
        "Total profit": "The total profit earned by the account.",
        "Total loss": "The total loss incurred by the account.",
        "Net": "The net value of the account (received - paid).",
        "Received": "The total amount received by the account.",
        "Paid": "The total amount paid from the account.",
        "P/L ratio": "The ratio of profit to loss in the account.",
        "Average profit": "The average percentage of profit over the period.",
        "Average loss": "The average percentage of loss over the period.",
        "Winning days": "The number of days with a positive balance.",
        "Losing days": "The number of days with a negative balance.",
        "Breakeven days": "The number of days the account broke even.",
        "Total": "The total amount of commission in the account.",
        "Rebate": "The rebate amount received by the account.",
        "Trade volume": "The total volume of trades conducted in the account.",
        "Market's used": "The number of different markets used in trading.",
        "Total trades": "The total number of trades conducted in the account.",
        "Total deposit": "The total amount deposited into the account.",
        "Total withdrawal": "The total amount withdrawn from the account.",
        "Referral payments": "The total payments made for referrals.",
    },
    ru: {
        "Tracking days": "Количество дней, в течение которых аккаунт активно отслеживался.",
        "Total days": "Общее количество дней, для которых учитывался аккаунт.",
        "Start date": "Дата начала работы аккаунта.",
        "Average balance": "Средний баланс аккаунта за период.",
        "Maximum balance": "Наибольший зафиксированный баланс аккаунта.",
        "Minimum balance": "Наименьший зафиксированный баланс аккаунта.",
        "The sum of total profit and total loss": "Общая сумма прибыли и убытков аккаунта.",
        "Total profit": "Общая прибыль, полученная аккаунтом.",
        "Total loss": "Общий убыток, понесённый аккаунтом.",
        "Net": "Чистая стоимость аккаунта (получено - оплачено).",
        "Received": "Общая сумма, полученная аккаунтом.",
        "Paid": "Общая сумма, выплаченная с аккаунта.",
        "P/L ratio": "Соотношение прибыли к убыткам аккаунта.",
        "Average profit": "Средний процент прибыли за период.",
        "Average loss": "Средний процент убытков за период.",
        "Winning days": "Количество дней с положительным балансом.",
        "Losing days": "Количество дней с отрицательным балансом.",
        "Breakeven days": "Количество дней, когда баланс аккаунта был равен нулю.",
        "Total": "Общая сумма комиссий аккаунта.",
        "Rebate": "Сумма возвратов, полученных аккаунтом.",
        "Trade volume": "Общий объем сделок, проведенных аккаунтом.",
        "Market's used": "Количество рынков, использованных в торговле.",
        "Total trades": "Общее количество сделок аккаунта.",
        "Total deposit": "Общая сумма внесенных средств.",
        "Total withdrawal": "Общая сумма снятых средств.",
        "Referral payments": "Общая сумма выплат за рефералов.",
    },
    de: {
        "Tracking days": "Die Anzahl der Tage, an denen das Konto aktiv verfolgt wurde.",
        "Total days": "Die Gesamtanzahl der Tage, für die das Konto betrachtet wird.",
        "Start date": "Das Datum, an dem das Konto begann.",
        "Average balance": "Der durchschnittliche Kontostand über den Zeitraum.",
        "Maximum balance": "Der höchste jemals verzeichnete Kontostand.",
        "Minimum balance": "Der niedrigste jemals verzeichnete Kontostand.",
        "The sum of total profit and total loss": "Die Gesamtsumme aus Gewinn und Verlust des Kontos.",
        "Total profit": "Der Gesamtgewinn des Kontos.",
        "Total loss": "Der Gesamtverlust des Kontos.",
        "Net": "Der Netto-Wert des Kontos (erhalten - bezahlt).",
        "Received": "Der Gesamtbetrag, den das Konto erhalten hat.",
        "Paid": "Der Gesamtbetrag, der vom Konto bezahlt wurde.",
        "P/L ratio": "Das Verhältnis von Gewinn zu Verlust im Konto.",
        "Average profit": "Der durchschnittliche Prozentsatz des Gewinns über den Zeitraum.",
        "Average loss": "Der durchschnittliche Prozentsatz des Verlusts über den Zeitraum.",
        "Winning days": "Die Anzahl der Tage mit einem positiven Kontostand.",
        "Losing days": "Die Anzahl der Tage mit einem negativen Kontostand.",
        "Breakeven days": "Die Anzahl der Tage, an denen das Konto ausgeglichen war.",
        "Total": "Die Gesamtprovisionssumme des Kontos.",
        "Rebate": "Die vom Konto erhaltene Rückvergütung.",
        "Trade volume": "Das gesamte Handelsvolumen des Kontos.",
        "Market's used": "Die Anzahl der verschiedenen Märkte, die gehandelt wurden.",
        "Total trades": "Die Gesamtanzahl der Trades des Kontos.",
        "Total deposit": "Die Gesamteinlage auf das Konto.",
        "Total withdrawal": "Der Gesamtbetrag, der vom Konto abgehoben wurde.",
        "Referral payments": "Die Gesamtsumme der Zahlungen für Empfehlungen.",
    },
    es: {
        "Tracking days": "El número de días que la cuenta ha sido rastreada activamente.",
        "Total days": "El número total de días en que se considera la cuenta.",
        "Start date": "La fecha en que se inició la cuenta.",
        "Average balance": "El saldo promedio de la cuenta durante el período.",
        "Maximum balance": "El saldo más alto registrado en la cuenta.",
        "Minimum balance": "El saldo más bajo registrado en la cuenta.",
        "The sum of total profit and total loss": "La suma total de ganancias y pérdidas de la cuenta.",
        "Total profit": "El total de ganancias obtenidas por la cuenta.",
        "Total loss": "El total de pérdidas sufridas por la cuenta.",
        "Net": "El valor neto de la cuenta (recibido - pagado).",
        "Received": "La cantidad total recibida por la cuenta.",
        "Paid": "La cantidad total pagada desde la cuenta.",
        "P/L ratio": "La relación entre ganancias y pérdidas en la cuenta.",
        "Average profit": "El porcentaje promedio de ganancias durante el período.",
        "Average loss": "El porcentaje promedio de pérdidas durante el período.",
        "Winning days": "El número de días con saldo positivo.",
        "Losing days": "El número de días con saldo negativo.",
        "Breakeven days": "El número de días en que la cuenta estuvo equilibrada.",
        "Total": "El monto total de la comisión en la cuenta.",
        "Rebate": "La cantidad de reembolso recibida por la cuenta.",
        "Trade volume": "El volumen total de operaciones realizadas en la cuenta.",
        "Market's used": "El número de mercados diferentes utilizados en operaciones.",
        "Total trades": "El número total de operaciones realizadas en la cuenta.",
        "Total deposit": "El monto total depositado en la cuenta.",
        "Total withdrawal": "El monto total retirado de la cuenta.",
        "Referral payments": "El total de pagos realizados por referencias.",
    },
};

